# Generated by Django 5.0.4 on 2024-04-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0002_alter_tarea_options_alter_tarea_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
